name: Peek
version: '${project.version}'
main: ict.minesunshineone.peek.PeekPlugin
api-version: '1.20'
authors: [MineSunshineOne]
description: 一个允许玩家观察其他玩家的插件
website: https://github.com/MineSunshineOne/Peek
folia-supported: true
softdepend: [PlaceholderAPI, ProtocolLib]

commands:
  peek:
    description: Peek插件的主命令
    usage: /peek <玩家名>
    aliases: [p]

permissions:
  peek.use:
    description: 允许使用peek命令
    default: op
  peek.bypass:
    description: 允许绕过私人模式
    default: op
  peek.nocooldown:
    description: 允许绕过冷却时间
    default: op
  peek.stats:
    description: 允许查看观察统计信息
    default: op